// <auto-generated />
using System;
using ApiSetUpFile.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiSetUpFile.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiSetUpFile.Model.E_Address", b =>
                {
                    b.Property<int>("DoorNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoorNum"));

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("E_Id")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeE_Id")
                        .HasColumnType("int");

                    b.Property<string>("LandMark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoorNum");

                    b.HasIndex("EmployeeE_Id");

                    b.ToTable("E_Address");
                });

            modelBuilder.Entity("ApiSetUpFile.Model.Employee", b =>
                {
                    b.Property<int>("E_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("E_Id"));

                    b.Property<DateTime?>("E_DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("E_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("E_Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("E_age")
                        .HasColumnType("int");

                    b.Property<string>("E_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("E_Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("ApiSetUpFile.Model.E_Address", b =>
                {
                    b.HasOne("ApiSetUpFile.Model.Employee", null)
                        .WithMany("E_Address")
                        .HasForeignKey("EmployeeE_Id");
                });

            modelBuilder.Entity("ApiSetUpFile.Model.Employee", b =>
                {
                    b.Navigation("E_Address");
                });
#pragma warning restore 612, 618
        }
    }
}
